name: build-and-test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 2 * * *'

jobs:
  previous-reports-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Modify reports
        run: npm run modify-reports
      - name: Reports Requiring Previous
        uses: ./
        with:
          report-path: './ctrf-reports/*.json'
          previous-results-report: true
          flaky-rate-report: true
          fail-rate-report: true
          insights-report: true
          slowest-report: true
          use-suite-name: true
          annotate: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()