name: suite

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npx tsc
      - name: Test suite folded with filepath
        run: node dist/index.js suite-folded ctrf-reports/ctrf-report.json --title "Suite folded"
      - name: Test suite folded with suite
        run: node dist/index.js suite-folded ctrf-reports/ctrf-report.json --title "Suite folded" --useSuite
      - name: Test suite folded no fails and filepath
        run: node dist/index.js suite-folded ctrf-reports/ctrf-report.json --title "Suite folded"
      - name: Test suite folded no fails and suite
        run: node dist/index.js suite-folded ctrf-reports/ctrf-report.json --title "Suite folded" --useSuite
      - name: Test suite folded pull request
        run: node dist/index.js suite-folded ctrf-reports/ctrf-report.json --title "Suite folded" --useSuite --pull-request
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test suite list
        run: node dist/index.js suite-list ctrf-reports/ctrf-report.json --title "Suite list" --useSuite
      - name: Test suite list no fails and filepath
        run: node dist/index.js suite-list ctrf-reports/ctrf-report.json --title "Suite list"
      - name: Test suite list no fails and suite
        run: node dist/index.js suite-list ctrf-reports/ctrf-report.json --title "Suite list useSuite" --useSuite
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: ctrf-report
          path: ctrf-reports/ctrf-report.json
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: custom-artifact-name
          path: ctrf-reports/ctrf-report-no-fails.json
